// Code generated by capnpc-go. DO NOT EDIT.

package kafkashape

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type CpHeader capnp.Struct

// CpHeader_TypeID is the unique identifier for the type CpHeader.
const CpHeader_TypeID = 0xd50180c828deee67

func NewCpHeader(s *capnp.Segment) (CpHeader, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CpHeader(st), err
}

func NewRootCpHeader(s *capnp.Segment) (CpHeader, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CpHeader(st), err
}

func ReadRootCpHeader(msg *capnp.Message) (CpHeader, error) {
	root, err := msg.Root()
	return CpHeader(root.Struct()), err
}

func (s CpHeader) String() string {
	str, _ := text.Marshal(0xd50180c828deee67, capnp.Struct(s))
	return str
}

func (s CpHeader) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CpHeader) DecodeFromPtr(p capnp.Ptr) CpHeader {
	return CpHeader(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CpHeader) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CpHeader) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CpHeader) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CpHeader) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CpHeader) Name() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s CpHeader) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CpHeader) SetName(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s CpHeader) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s CpHeader) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CpHeader) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// CpHeader_List is a list of CpHeader.
type CpHeader_List = capnp.StructList[CpHeader]

// NewCpHeader creates a new list of CpHeader.
func NewCpHeader_List(s *capnp.Segment, sz int32) (CpHeader_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CpHeader](l), err
}

// CpHeader_Future is a wrapper for a CpHeader promised by a client call.
type CpHeader_Future struct{ *capnp.Future }

func (f CpHeader_Future) Struct() (CpHeader, error) {
	p, err := f.Future.Ptr()
	return CpHeader(p.Struct()), err
}

type CpHttpPair capnp.Struct

// CpHttpPair_TypeID is the unique identifier for the type CpHttpPair.
const CpHttpPair_TypeID = 0x94026d0e4fdf394f

func NewCpHttpPair(s *capnp.Segment) (CpHttpPair, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 15})
	return CpHttpPair(st), err
}

func NewRootCpHttpPair(s *capnp.Segment) (CpHttpPair, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 15})
	return CpHttpPair(st), err
}

func ReadRootCpHttpPair(msg *capnp.Message) (CpHttpPair, error) {
	root, err := msg.Root()
	return CpHttpPair(root.Struct()), err
}

func (s CpHttpPair) String() string {
	str, _ := text.Marshal(0x94026d0e4fdf394f, capnp.Struct(s))
	return str
}

func (s CpHttpPair) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CpHttpPair) DecodeFromPtr(p capnp.Ptr) CpHttpPair {
	return CpHttpPair(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CpHttpPair) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CpHttpPair) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CpHttpPair) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CpHttpPair) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CpHttpPair) Method() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s CpHttpPair) HasMethod() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CpHttpPair) SetMethod(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s CpHttpPair) Path() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s CpHttpPair) HasPath() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CpHttpPair) SetPath(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s CpHttpPair) Version() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s CpHttpPair) HasVersion() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s CpHttpPair) SetVersion(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s CpHttpPair) StatusCode() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s CpHttpPair) SetStatusCode(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s CpHttpPair) Reason() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return []byte(p.Data()), err
}

func (s CpHttpPair) HasReason() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s CpHttpPair) SetReason(v []byte) error {
	return capnp.Struct(s).SetData(3, v)
}

func (s CpHttpPair) ReqHeaders() (CpHeader_List, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return CpHeader_List(p.List()), err
}

func (s CpHttpPair) HasReqHeaders() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s CpHttpPair) SetReqHeaders(v CpHeader_List) error {
	return capnp.Struct(s).SetPtr(4, v.ToPtr())
}

// NewReqHeaders sets the reqHeaders field to a newly
// allocated CpHeader_List, preferring placement in s's segment.
func (s CpHttpPair) NewReqHeaders(n int32) (CpHeader_List, error) {
	l, err := NewCpHeader_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return CpHeader_List{}, err
	}
	err = capnp.Struct(s).SetPtr(4, l.ToPtr())
	return l, err
}
func (s CpHttpPair) RespHeaders() (CpHeader_List, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return CpHeader_List(p.List()), err
}

func (s CpHttpPair) HasRespHeaders() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s CpHttpPair) SetRespHeaders(v CpHeader_List) error {
	return capnp.Struct(s).SetPtr(5, v.ToPtr())
}

// NewRespHeaders sets the respHeaders field to a newly
// allocated CpHeader_List, preferring placement in s's segment.
func (s CpHttpPair) NewRespHeaders(n int32) (CpHeader_List, error) {
	l, err := NewCpHeader_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return CpHeader_List{}, err
	}
	err = capnp.Struct(s).SetPtr(5, l.ToPtr())
	return l, err
}
func (s CpHttpPair) ReqBody() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return []byte(p.Data()), err
}

func (s CpHttpPair) HasReqBody() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s CpHttpPair) SetReqBody(v []byte) error {
	return capnp.Struct(s).SetData(6, v)
}

func (s CpHttpPair) RespBody() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return []byte(p.Data()), err
}

func (s CpHttpPair) HasRespBody() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s CpHttpPair) SetRespBody(v []byte) error {
	return capnp.Struct(s).SetData(7, v)
}

func (s CpHttpPair) SourceIp() (string, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.Text(), err
}

func (s CpHttpPair) HasSourceIp() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s CpHttpPair) SourceIpBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.TextBytes(), err
}

func (s CpHttpPair) SetSourceIp(v string) error {
	return capnp.Struct(s).SetText(8, v)
}

func (s CpHttpPair) DestIp() (string, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return p.Text(), err
}

func (s CpHttpPair) HasDestIp() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s CpHttpPair) DestIpBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return p.TextBytes(), err
}

func (s CpHttpPair) SetDestIp(v string) error {
	return capnp.Struct(s).SetText(9, v)
}

func (s CpHttpPair) AktoAccountId() (string, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return p.Text(), err
}

func (s CpHttpPair) HasAktoAccountId() bool {
	return capnp.Struct(s).HasPtr(10)
}

func (s CpHttpPair) AktoAccountIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return p.TextBytes(), err
}

func (s CpHttpPair) SetAktoAccountId(v string) error {
	return capnp.Struct(s).SetText(10, v)
}

func (s CpHttpPair) Source() (string, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return p.Text(), err
}

func (s CpHttpPair) HasSource() bool {
	return capnp.Struct(s).HasPtr(11)
}

func (s CpHttpPair) SourceBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return p.TextBytes(), err
}

func (s CpHttpPair) SetSource(v string) error {
	return capnp.Struct(s).SetText(11, v)
}

func (s CpHttpPair) DaemonsetId() (string, error) {
	p, err := capnp.Struct(s).Ptr(12)
	return p.Text(), err
}

func (s CpHttpPair) HasDaemonsetId() bool {
	return capnp.Struct(s).HasPtr(12)
}

func (s CpHttpPair) DaemonsetIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(12)
	return p.TextBytes(), err
}

func (s CpHttpPair) SetDaemonsetId(v string) error {
	return capnp.Struct(s).SetText(12, v)
}

func (s CpHttpPair) ProcessName() (string, error) {
	p, err := capnp.Struct(s).Ptr(13)
	return p.Text(), err
}

func (s CpHttpPair) HasProcessName() bool {
	return capnp.Struct(s).HasPtr(13)
}

func (s CpHttpPair) ProcessNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(13)
	return p.TextBytes(), err
}

func (s CpHttpPair) SetProcessName(v string) error {
	return capnp.Struct(s).SetText(13, v)
}

func (s CpHttpPair) Tag() (string, error) {
	p, err := capnp.Struct(s).Ptr(14)
	return p.Text(), err
}

func (s CpHttpPair) HasTag() bool {
	return capnp.Struct(s).HasPtr(14)
}

func (s CpHttpPair) TagBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(14)
	return p.TextBytes(), err
}

func (s CpHttpPair) SetTag(v string) error {
	return capnp.Struct(s).SetText(14, v)
}

func (s CpHttpPair) TimeUnix() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s CpHttpPair) SetTimeUnix(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s CpHttpPair) VxlanId() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s CpHttpPair) SetVxlanId(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s CpHttpPair) Direction() int32 {
	return int32(capnp.Struct(s).Uint32(16))
}

func (s CpHttpPair) SetDirection(v int32) {
	capnp.Struct(s).SetUint32(16, uint32(v))
}

func (s CpHttpPair) ProcessId() uint32 {
	return capnp.Struct(s).Uint32(20)
}

func (s CpHttpPair) SetProcessId(v uint32) {
	capnp.Struct(s).SetUint32(20, v)
}

func (s CpHttpPair) SocketId() uint32 {
	return capnp.Struct(s).Uint32(24)
}

func (s CpHttpPair) SetSocketId(v uint32) {
	capnp.Struct(s).SetUint32(24, v)
}

func (s CpHttpPair) IsPending() bool {
	return capnp.Struct(s).Bit(224)
}

func (s CpHttpPair) SetIsPending(v bool) {
	capnp.Struct(s).SetBit(224, v)
}

func (s CpHttpPair) EnableGraph() bool {
	return capnp.Struct(s).Bit(225)
}

func (s CpHttpPair) SetEnableGraph(v bool) {
	capnp.Struct(s).SetBit(225, v)
}

// CpHttpPair_List is a list of CpHttpPair.
type CpHttpPair_List = capnp.StructList[CpHttpPair]

// NewCpHttpPair creates a new list of CpHttpPair.
func NewCpHttpPair_List(s *capnp.Segment, sz int32) (CpHttpPair_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 15}, sz)
	return capnp.StructList[CpHttpPair](l), err
}

// CpHttpPair_Future is a wrapper for a CpHttpPair promised by a client call.
type CpHttpPair_Future struct{ *capnp.Future }

func (f CpHttpPair_Future) Struct() (CpHttpPair, error) {
	p, err := f.Future.Ptr()
	return CpHttpPair(p.Struct()), err
}

const schema_f461b3f155baae22 = "x\xda|\xd4?\x88\x1cU\x1c\x07\xf0\xef\xf7\xbd\xd9?" +
	"w\xb7\x7fn\xf2\xde\xc5\x08\xc2iH\x11\x83\xd1Dl" +
	"Ls\x9a\x14f-\xcc\xed\x0di\xc4f\xb2\xf3\xb8]" +
	"r;3\x99\x99\x8d\x17PrB\x1a!\x82\x85\x8d\xa5" +
	"`\xc0\xca\xc6F\x04!\x82E\x844B\x02i\xd4;" +
	"\xb0P\x08\xc2\xc9\x09\xb1\x08#\xbf1\xbbwX\xd8\xbd" +
	"\xf7\xe1\xbb\xbf\xfd\xfd\xde.\xbfS;|\xcd;\xdd~" +
	"JA\xf5\x8f\xd4\xea\xe5\x85W\x7f\xb9\xd0\x19\xabO\xd0" +
	"_\xa2W\x1e\xfd\xf2\x9b\x8b\xbb_\x85{\xa8u\x1b\xc0" +
	"\xe9]E\xff\xb1\x1c\xfe\xee\xd6\xc0r\xfd\x8f\x9f\x8f\xdf" +
	"\xd9\xe2}\xf8K<\x10U\x0d\xc0|Z\xff\xd3\xdc\xaa" +
	"\xcb\xe9\xb3\xfa\xbb8Y\xe6\x83\xa1\x1b\x87/\x0duQ" +
	"\xa4\xe3|\xfd\xc5A\x98\xc6\xe9\x99s\xe9\xf9\xa2HW" +
	"\xc3Q\x86U\xb2\xff\x8e\xf6\x00\x8f\x80\x99\xa83@\x90" +
	"*\xcd\xe0=\xa5\xe8\x93\x96\xe2\xd7\xd4\x09 (\xc4\xb7" +
	"\xc4\x95\xb2T\x80y_\x9d\x05\x82M\xf1\x1bJ\x91\xda" +
	"R\x03\xe6\x03\xf56\x10l\x09\xdf\x94\xb8\xa7-=\xc0" +
	"|X\x95\xbf!\xfe\xb1x\xcd\xb3\xac\x01\xe6\xa3*\x7f" +
	"S\xfc\x0b\xf1z\xcd\xb2\x0e\x98[\xea\x12\x10|.~" +
	"[\xbcQ\xb7\x94\xd9\xbe\xad\xbe\xf6k\xf1\xef\xc5\x9b\x0d" +
	"\xcb&`\xbeSo\x02\xc1m\xf1\xbb\xe2sM\xcb9" +
	"\xc0\xfcP\xf9\x1d\xf1{\xe2\xf3s\x96\xf3\x80\xf9\xb1\xea" +
	"\xe7\xae\xf8\x03\xf1\x85y\xcb\x05\xc0\xdcW\x19\x10\xdc\x13" +
	"\xdf\x16o-X\xb6\x00\xf3S\x95\x7f \xfe\xabx\xbb" +
	"e\xd9\x06\xccN\xd5\xe7\xb6\xf8C\xf1N\xdb\xb2\x03\x98" +
	"\xdf+\xffM|O\xbc\xdb\xb1\xec\x02fW\x1d\x05\x82" +
	"\x87\xe2\x8f\xc4\x17i\xb9\x08\x98\xbf\xaa>\xf7\x94\xe6\x9a" +
	"V\xf4}Z\xfa\x80y\\\x8d\xfbH\xe2\x9e\xf8!\xcf" +
	"\xf2\x10`\xa8\xd7\x805\xad\x19\xb4\x84M\xcd\xd2\x00f" +
	"N8h\x8a[q[\xb7\xb4\x80\xf1\xb5T_\x14\x7f" +
	"F|i\xdbr\x090OW\xf9#\xe2\xc7\xc4\x0f\xef" +
	"X\x1e\x06\xccsZ\xba\x7fV\xfc\x05\xad\xb82v\xc5" +
	"0\x89\xd8\x86b\x1b\xec\xa6a1\x9c^\xae_uY" +
	">J\xe2\xe9\xbd\xcc\x8b\xb0\x98\xe4\xe7\x12\xe8\xc8\xd1\x83" +
	"\xa2\x07\xaed.\xcc\x0fd2w\xe5\xbc\x0b#\x07\x9d" +
	"\xe5\xec\x80\xab\x9a\\\xdc\xffw\x83\x82e\xe6\xf2Tb" +
	"h\xb8\xff\x89]\xcf\xdc\x95\xb3It\xed@\xf1<\x15" +
	"\x00\xb0\xdfT2\xc9\x06\xae\x97\x8a\xb5\xa0\xd8\x02W\"" +
	"\x97\x17\xbdtz-\xc3\xcbE\xf2\xfa`\x90`y\x12" +
	"\x17\xbdh\x16\xfb\xf7\xa3\xb3X\x14\xbaq\x12\xe7\x0e\x8d" +
	"\x03\xa12\xcd\x92\x81\xcb\xf3\xb7\xd0\x08\xc7\xb3l\xa3\x08" +
	"\xd7g\x89b4v\x17\xe3\xd1\xa6tP\x83bM\x9e" +
	"ns#\x8c{\xd1\xf4\x95\xcah\x94\xb9A1J\xc0" +
	"xfO*\xf7\xc0\x88M(6\xabi\x06\x97]\xd1" +
	"\x8b\xa4\xd6\xd4F\xf9\xaa\x8b\xa3Q\x0c\xae\x93P$X" +
	"\xba8\xbc\xb4\xe1\xde\xc8\xd0\x08\xd3\xe1L\xa7\x8bA\xfd" +
	"w1,\xcbO\x92\xc9ZhN\xd7\x82\xff\xfc\x09\xa0" +
	"\x7fL\xb3\x7fj\x7f'\xf8'_\x06\xfa\xc75\xfb\xaf" +
	"(vc\x99\xf8\xc9;/_\x0d7&\xb3\xdb?\x01" +
	"\x00\x00\xff\xff\x19J\xf3\xd7"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_f461b3f155baae22,
		Nodes: []uint64{
			0x94026d0e4fdf394f,
			0xd50180c828deee67,
		},
		Compressed: true,
	})
}
